### ISSUE TITLE
accentIconTheme is deprecated!

### ISSUE THREAD

**Issue by sellch00k** [peiffer-innovations/json_theme#22] opened 2021-03-03 16:30 UTC
There is some deprecated convertions

Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.

**Comment by jpeiffer** [comment] 2021-04-30 18:15
I'm not even sure what this is trying to say the issue actually is.

There are a few references to deprecated things in the library, and that's by design.  Removing those encoders and decoders would break users of the library.  So if the library supported it before, and Flutter still supports it (even if it's deprecated), the library keeps the reference; again by design.

However... in this particular case, the `accentIconTheme` is actually not even marked as deprecated in the actual Dart code.  So while, yes, there are known references for deprecated things that are annotated to ignore the warnings this doesn't even appear to be one of them.

**Closed by jpeiffer** 2021-04-30 18:15 UTC
